### PR TITLE
More oredict entries

### PR DESCRIPTION
**Pull request by RCXcrafter**
I added some more entries to the ore dictionary and modified some recipes to make use of the ore dictionary.

If you want anything changed, please tell me. I did this because I wanted to save you work, not the opposite.

### CODE REVIEW

**Comment by TheCyberBrick** [comment]
I haven't forgotten about this but I had no time yet. Will look at this soon :)

**Comment by iLexiconn** [comment]
We still haven't forgotten.... I think?

**Comment by TheCyberBrick** [comment]
Yes, you thought correctly

**Comment by RCXcrafter** [comment]
I have fixed the broken recipes, should I make new pull request now? I can't seem to reopen this one.

**Comment by iLexiconn** [comment]
Yes please :)

**Pull request merged**
